// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Cita struct {
	ID        int32
	ClienteID int32
	UsuarioID int32
	FechaHora time.Time
	Estado    string
}

type Cliente struct {
	ID       int32
	Nombre   string
	Telefono sql.NullString
	Email    sql.NullString
}

type Servicio struct {
	ID     int32
	Nombre string
	Precio string
}

type Usuario struct {
	ID       int32
	Nombre   string
	Email    string
	Hash     string
	Rol      string
	CreadoEn time.Time
}

type Venta struct {
	ID       int32
	CitaID   sql.NullInt32
	Total    string
	CreadoEn time.Time
}

type VentaItem struct {
	ID         int32
	VentaID    int32
	ServicioID int32
	Cantidad   int32
	PrecioUnit string
}
