// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usuarios.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO usuarios (nombre, email, hash, rol)
VALUES ($1, $2, $3, $4)
RETURNING id, nombre, email, hash, rol, creado_en
`

type CreateUserParams struct {
	Nombre string
	Email  string
	Hash   string
	Rol    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Nombre,
		arg.Email,
		arg.Hash,
		arg.Rol,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Email,
		&i.Hash,
		&i.Rol,
		&i.CreadoEn,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, nombre, email, hash, rol, creado_en FROM usuarios
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Email,
		&i.Hash,
		&i.Rol,
		&i.CreadoEn,
	)
	return i, err
}
